services:
  frontend:
    build:
      context: ./Promact_Customer_Success/Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Promact_Customer_Success/Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db  
volumes:
  mongo_data:
